apiVersion: 1

datasources:
  - name: ClickHouse
    type: clickhouse-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: default
      port: 8123
      protocol: http
      username: default
    secureJsonData:
      password: clickhouse
    isDefault: true
    editable: true
