name: 'reverse_etl'
version: '1.0.0'
config-version: 2

profile: 'reverse_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  reverse_etl:
    staging:
      +materialized: view
      +database: iceberg
      +schema: raw
    marts:
      +materialized: table
      +format: parquet

