name: 'order_metrics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'order_metrics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  order_metrics:
    local_resources:
      # only work in target.name == local-setup, else false
      +enabled: "{{ true if target.name == 'local-setup' else false }}"
      central_order_descriptors_odp:
        +database: delta
        +schema: central_order_descriptors_odp


# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  order_metrics:
    +database: delta  # always use delta catalog
    +materialized: table
    +on_table_exists: drop
    +views_enabled: false # https://github.com/trinodb/trino/pull/11763 Views not enabled in delta yet
    internal:
      +schema: central_order_metrics_internal
    odp:
      +schema: central_order_metrics_odp
